print("Hola" + "Javier")
print("Hola " + "Javier") 
print("Hola" + " Javier") 
print("Hola" + " " + "Javier") 
print("Hola \"Javier\"")
print("Hola\nJavier")
print("Hola\n\tJavier")
print("Javier isn\'t a bad person")
print("Mostramos barra invertida: \\")